dev-requirements.txt
landoui/dockerflow.py
tests/test_dockerflow.py

Adds the py-flakes library to the dev-requirements.
py-flakes provides some extra fixtures (mainly the client fixutre)
which allows us to easily make requests to the test application and
check the response.
The tests added should all pass, and are based on those from the
lando-api writen by mars.
If the tests do not pass when running `invoke test` intitally, then
most likely you will have to rebuild the test container. Running
`docker-compose build --no-cache` sometimes is not enough, because the
test containers use a different project scope. Instead to run:
`docker-compose -p testlandoui build --no-cache` to resolve the issue.

Add tests for the dockerflow endpoints.

---

docker-compose.yml

We can't use '.dev' or '.local' to name hosts for local development.
'.dev' is a TLD and doesn't work under Vagrant (see https://github.com/Varying-Vagrant-Vagrants/VVV/issues/544).
'.local' clashes with MDNS.
According to RFC 6761 '.test' is reserved for local networks, so
let's use that.

Use .test for local development

---

landoui/app.py
tasks.py
tests/test_dockerflow.py

The old invoke file was based on our invoke file from our conduit hg monorepo - which had many different containers building and running in unision.
In our case we're using invoke simply as an alias for docker-compose to prevent us from having to type everything out.
The old invoke file created a new project space for the test containers which was causing problems because changes to the Dockerfile or the python requirements wouldn't cause rebuild of images in the testproject space (unknown reason why). So what would happen is I would run `invoke test` but I would get a test failure even though everything looked fine on my end - the underlying cause was that the test container wasn't refreshed and it was not obvious when this happened.
This commit changes the tasks.py file to use the same …

Update invoke tasks and fix broken tests

---

landoui/assets_src/assets.yml

Assets were being included in the bundle css and js files because of the way were we defining our assets manifest file. This PR changes things to be more explicit.
I've confirmed that the before and after is appropriate: there are no duplicates in the newly generated static assets.
Fixes #33 and #34.

Fix static assets being included twice

---

landoui/app.py
landoui/assets_src/assets.yml
landoui/assets_src/css/colors.scss
landoui/assets_src/css/components/Navbar.scss
landoui/assets_src/js/components/Navbar.js
landoui/assets_src/js/main.js
landoui/assets_src/js/pages/RevisionPage.js
landoui/helpers.py
landoui/pages.py
landoui/revisions.py
landoui/templates/home.html
landoui/templates/partials/navbar.html
landoui/templates/revision.html
landoui/templates/signout.html

- Make sure you setup and run Lando API (https://github.com/mozilla-conduit/lando-api)
- Add the URL to Lando API in Lando UI's environment variable `LANDO_API_URL`. This can be done via a docker-compose.override.yml file.
- Add values for the OIDC_*  environment variables. You can use a personal Auth0 account or any other values you like. PM @purelogiq if you want to use his personal Auth0 instance. (In production we will of course be using Mozilla's Auth0 instance).
- Run `docker-compose up --build` and view the UI. Try logging in with auth0. 
- See **screenshots** at the bottom of this PR. Post feedback back here 😃 
- Known issues: The signout page is lame, this will be fixed in a separate card/PR. The settings modal is just a placeholder that will be used in another PR. I only added …

Integrate Auth0 login flow into the navigation bar.

---

docker/Dockerfile-dev

The most recent build of master failed because it could not install the latest sass. As you can see, sass was updated yesterday to 3.5 (https://rubygems.org/gems/sass/versions/3.5.0).
This PR locks sass to a version (3.4.25) that was working previously.

Lock sass version to 3.4.25

---

circle.yml

Make the CircleCI build tag and push the 'latest' image tag to Docker
Hub so that we can use the latest image in the demo.

Tag the latest image in Docker Hub

---

docker-compose.yml
landoui/app.py
landoui/pages.py
requirements/common.txt

Move the log configuration code into the `app` module so that we can log application startup information.
Configure application logging using Sentry.  Boilerplate code was copied from https://github.com/mozilla-conduit/lando-api/pull/26.
Verified working using docker and our real Sentry account.  We should be able to ship this.

Move logging config code / Use Sentry to log application errors

---

landoui/app.py

flask-pyoidc uses the PREFERRED_URL_SCHEME to generate the redirect url, so we'll have to set it properly to get it all working!

Set app PREFERRED_URL_SCHEME based on USE_HTTPS environment variable

---

tests/conftest.py

Turn on the Flask TESTING setting so that exceptions within the app bubble up to the test runner.  Otherwise Flask will hide the exception behind a generic HTTP 500 response, and that makes writing and debugging tests much harder.

Fix test exception propagation

---

landoui/app.py
landoui/assets_app.py
landoui/dockerflow.py
landoui/revisions.py
landoui/wsgi.py
tests/conftest.py
tests/test_dockerflow.py
tests/test_revisions.py

Make the Lando UI `__heartbeat__` endpoint check Lando API for a valid connection.
This PR includes PR https://github.com/mozilla-conduit/lando-ui/pull/49 to fix test propagation.

heartbeat-checks-lando-api

---

landoui/dockerflow.py

The dockerflow health and version endpoints should instruct the caller
not to cache any results. This commit sets Cache-Control to properly
disable caching.
Closes #51

dockerflow: set cache-control header in responses.

---

CODE_OF_CONDUCT.md

As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:
1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional …

docs: add Mozilla Code of Conduct.

---

README.md

Make the setup instructions in the README match the Auth0 UI.
Include setup instructions for creating a user account for the
developer's new lando-ui service.

docs: update dev setup instructions

---

docker-compose.yml
landoui/app.py
landoui/revisions.py
landoui/templates/stack/stack.html

Add a feature flag to turn the sec-approval workflow on and off. We
verify the flag is working by adding a comment to the HTML document if
the feature is turned on and the revision is secure.

[sec-approval/1] add a sec-approval workflow feature flag (bug 1550013)

---

tasks.py
tests/test_py3_codequality.py

YAPF will happily check the style of all files in the .git directory.
This causes our test suite to fail if a third party tool puts something
in .git that doesn't match our project's code style. YAPF should just
ignore .git/.

tests: tell YAPF to ignore the .git directory

---

landoui/templates/partials/navbar.html

The call to the user settings form CSRF token raises an exception when
CSRF protection is switched off by the test suite.  Calling
form.csrf_token as an attribute instead of a method handles CSRF
protection correctly.

ui: fix CSRF api call in the user settings form

---

landoui/app.py

Log an Ops-friendly message after the application starts successfully.

app: add ops-friendly app startup message

---

landoui/assets_src/js/components/LandingPreview.js

Due to some browser differences, when a button is disabled in its own click
handler, if that button results in form submission the form will not be
submitted in Safari or Chrome.
This issue is solved by moving the disabling of the button to the form
submit event handler.

landing-preview: fix landing button not working in Safari or Chrome (bug 1570960)

---

tests/conftest.py
tests/test_sec_approval_workflow.py

Add a basic acceptance test suite that mocks Lando API responses and can
validate Lando UI's HTML output.

[sec-approval/2] add a basic acceptance test suite (bug 1550013)

---

landoui/assets_src/css/pages/StackPage.scss
landoui/assets_src/js/components/LandingPreview.js
landoui/assets_src/js/components/RequestSubmitted.js
landoui/assets_src/js/main.js
landoui/forms.py
landoui/revisions.py
landoui/templates/stack/partials/landing-preview.html
landoui/templates/stack/stack.html
tests/test_sec_approval_workflow.py

Add a form for requesting sec-approval for a revision's commit message.
Reorganize the Land Preview forms to accommodate the new sec-approval
form. Add a dummy HTTP endpoint to accept requests from the new form.

ui: add a form for requesting sec-approval (bug 1550013)

---

docker-compose.yml
landoui/app.py
landoui/assets_src/css/pages/QueuePage.scss
landoui/assets_src/js/components/Queue.js
landoui/assets_src/js/main.js
landoui/pages.py
landoui/template_helpers.py
landoui/templates/queue/queue.html
tests/test_template_helpers.py

Adds the initial queue of landings on the index page.
This queue will only show up when the ENABLE_EMBEDDED_TRANSPLANT_UI
flag is enabled and the user is logged in.
- In the future we can remove both of these requirements.
The landing queue currently fakes data from the api. Once the API
changes are ready we will update the UI to actually query real queue
data. The expected data format can be seen in `queue.html`.
Clicking on a revision will take the user to the revision page where
they will be able to cancel, prioritize, and see extra details about the
landing. These features will be implemented in a separate PR.

queue: add initial queue of landings on home page (bug 1587138)

---

landoui/template_helpers.py
landoui/templates/stack/partials/timeline.html

This bug was due to the statuses of `LandingJob` objects being uppercase
vs. the statuses of legacy transplants being lowercase.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1649466.

timeline: show link to changeset for local transplants (bug 1649466)

---

landoui/assets_src/js/components/Timeline.js
landoui/revisions.py
landoui/templates/stack/partials/timeline.html

- add UI elements to allow user to cancel a landing job
- add cancel endpoint
See https://github.com/mozilla-conduit/lando-api/pull/107 for API implementation.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1503000.
Example of a job being cancelled:
Example of a job that can not be cancelled (already landed). Note that a future implementation will update the button to reflect the current state.

landing jobs: ability to submit a cancel request from UI (bug 1503000)

---

landoui/assets_src/js/components/LandingPreview.js
landoui/forms.py
landoui/revisions.py
landoui/templates/stack/partials/landing-preview.html
landoui/templates/stack/stack.html

Adds a "flags" section to the preview landing dialog, showing the user available flags to append to the commit message for supported repos.

stacks: add support for DONTBUILD flag (bug 1642939)

---

landoui/assets_src/js/components/LandingPreview.js
landoui/revisions.py
landoui/templates/stack/partials/landing-preview.html
tests/test_sec_approval_workflow.py

- update help text to reflect that all commit messages will be updated
- update heading to reflect "advanced settings"
- clarify check box behaviour in wording
stacks: minor copy change in landing preview modal (bug 1658481)
stacks: add help text support to flags (bug 1658019) 
Should land with https://github.com/mozilla-conduit/lando-api/pull/134

stacks: fixes to DONTBUILD (bug 1658481, bug 1661134, bug 1658019)

---

landoui/assets_src/css/lando.scss
landoui/assets_src/css/pages/StackPage.scss
landoui/assets_src/js/components/Timeline.js
landoui/templates/stack/partials/timeline.html

- show failed paths when there is a merge conflict
- show and link to revision which caused the conflict in the stack
- link to changeset of source path
- show rejected hunks (collapsible)
- collapse raw error output if breakdown is available

timeline: add support for error breakdown (bug 1686869)

---

landoui/templates/stack/partials/timeline.html

This change is mainly for backwards compatibility with older revisions
that may have invalid paths in the error breakdown.

timeline: check failed paths against rejected paths (bug 1696396)

---

landoui/errorhandlers.py

Adds a conditional to the Lando-API exception handlers that
shows a maintenance-mode specific title when a 503 error is
returned from Lando. This should inform users that Lando is
unavailable at the moment and is not broken.

errors: add a maintenance-mode specific title to serverside error handlers (Bug 1724769)

---

landoui/template_helpers.py
landoui/templates/stack/stack.html

Adds a global template function to check if the Phabricator
API token is available in the local host. This function simply
checks the value of `get_phabricator_api_token` is not `None`.
If the token is present, the uplift request button is added to
the landing dialog.

stacks: hide uplift request form behind Phab API token (Bug 1794606)

---

landoui/revisions.py

Despite the token not being required on the API side, the UI side
has `require_auth0=True`. This results in an `AssertionError`
when trying to add the token to the request. Unmark the API call
as requiring Auth0.

uplift: do not require auth0 token to populate uplift repo list (Bug 1797168)

---

landoui/app.py
landoui/errorhandlers.py
landoui/sentry.py
requirements.in
requirements.txt

Migrates Lando-ui from `raven` to `sentry-sdk` for our
Sentry integration. Mostly copy how Lando-API configures
Sentry via `sentry_sdk.init()`, but leave parsing of some
custom environment variables the same.

sentry: migrate from `raven` to `sentry-sdk` (Bug 1797311)

---

landoui/landoapi.py

Sentry is categorizing any unexpected response as a `JSONDecodeError`
because those responses are typically returning HTML webpages or empty
response bodies. Catch the JSONDecodeError early and attempt to raise
the more detailed exception from `requests` if possible.

landoapi: raise `requests` exception instead of `JSONDecodeError`

---

landoui/forms.py
landoui/revisions.py
landoui/templates/stack/stack.html

Pass the `revision_id` from the stack page through to the
uplift endpoint instead of `landing_path`.

uplift: change `landing_path` field to `revision_id` (Bug 1801926)

---

docker-compose.yml
docker/Dockerfile-dev

Mount the full Lando-UI source directory into `/app` in the
container to conform with how Lando-API mounts volumes. Add
`FLASK_DEBUG=1` to the environment to enable hot-reloading.

docker: make Python code hot-reload in local environment (Bug 1826785)

---

.circleci/config.yml

Using CIRCLE_TAG in development and staging image tags to build immutable tags for deployment.

fix(circleci): Using CIRCLE_TAG in develop and stage image tags (bug 1870070)

---

.circleci/config.yml

`CIRCLE_TAG` is not populated when we want to create dev and stage images. 
Using `CIRCLE_SHA1` instead of `CIRCLE_TAG` for dev and stage tag names

fix: Using SHA1 in dev/stage image name instead of tag

---

landoui/assets_src/js/components/Stack.js
landoui/templates/stack/stack.html

Create a new modal div that contains the uplift request form. Add a new
button for requesting uplifts next to the "Preview Landing" button.
Remove the code that allows pressing the "Preview Landing" button
even when the stack is not landable since we no longer have the
uplift button behind that modal.

stack: move the uplift request form into a separate modal (Bug 1801959)

---

landoui/templates/stack/partials/landing-preview.html
landoui/templates/stack/partials/revision-status.html

As part of the checks refactor we will eventually support displaying
multiple blockers in the front end. Add a shim so Lando-UI can handle
output from before and after the refactor PR in LandoAPI is landed
and deployed.

landing-preview: add a shim to display `blockers` dryrun info if available (Bug 1888188)

---

landoui/app.py
landoui/assets_app.py
landoui/assets_src/css/pages/TreestatusPage.scss
landoui/assets_src/js/components/Treestatus.js
landoui/assets_src/js/main.js
landoui/dev_app.py
landoui/forms.py
landoui/helpers.py
landoui/landoapi.py
landoui/template_helpers.py
landoui/templates/partials/navbar.html
landoui/templates/treestatus/log.html
landoui/templates/treestatus/new_tree.html
landoui/templates/treestatus/recent_changes.html
landoui/templates/treestatus/trees.html
landoui/templates/treestatus/update_trees.html
landoui/treestatus.py
landoui/wsgi.py
tests/conftest.py
tests/test_treestatus.py

Implement a Treestatus UI in Lando. All endpoints in the new
interface are namespaced under `/treestatus`. The main components
are as follows.
The main Treestatus page displays all trees and their current statuses.
When authenticated, each tree can be selected for updating via a checkbox,
or a "select all trees" button is available for CI-wide tree closures.
The tree selections are forwarded to the update form when "Update trees"
is selected.
The "update trees" view implements a form for updating the status of
trees. Trees can be set to open, closed and "approval required". When
the status is being set to a non-open state, a reason and reason
category must be specified. The form presents a "remember this change"
option which can be used to easily revert the change at a later time.
For …

treestatus: implement Treestatus UI (Bug 1817473)

---

landoui/templates/stack/partials/revision-status.html

In the original revision I added a `blocked_reason` variable to avoid repeated
code, however I forgot to update the template to actually use the variable.

revision-status: use `blocked_reason` variable instead of pre-refactor key (Bug 1888188)

---

landoui/treestatus.py

In other parts of Lando, before making an API call that uses
the `require_auth0` kwarg, we do an explicit check that the
user is authenticated and handle unauthenticated requests
appropriately. This was overlooked in implementing the Treestatus
UI and is resulting in errors in Sentry since we instead
only discover the missing credentials when making the request,
resulting in an unhandled exception. Add an explicit check
to each handler which makes an `auth0_required` API call.

treestatus: check for user authentication before `require_auth0` API calls (Bug 1896642)

---

landoui/treestatus.py

When calling out to the tree logs endpoint, we do not properly
handle non-2XX reponse codes within LandoUI, as those throw a
`LandoAPIError` which must be handled. Add a `try/except` block
around the error to properly handle tree names that return 404
from LandoAPI and other errors.

treestatus: handle 404 from tree logs reponse properly (Bug 1896642)

---

landoui/template_helpers.py
landoui/templates/treestatus/trees.html

Add a new `is_treestatus_user` template helper which checks for
membership in the Treestatus Mozillians groups. Switch to using
this new function to determine if Treestatus editing elements of
the UI should be shown.

templates: hide Treestatus editing capabilities from unprivileged users (Bug 1901484)
